# Basic
title: 阿谦
subtitle: 个人站
description: welcome
# 头像里面的标题
avatarTitle: TonyYY
# 头像里面的描述
avatarDesc: iOS Dev
url: "http://shangqianForFun"

# Comment
comment:
    # disqus: leopard
    # duoshuo: leopard 

# Social
social:
    QQ: 429669972 
    github: shangqianForFun
    # twitter: 
    mail: qianqian11_hi@163.com

permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:

    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
# gems: [jekyll-paginate]
# paginate: 20
# paginate_path: "page/:num/"


